import pandas as pd
import streamlit as st

from components.data_loader import load_dashboard_data

from components.metrics import (
    total_customers,
    total_monetary,
    total_segments,
    high_value_customer_percentage,
    high_value_monetary_percentage,
    kmeans_review_percentage,
    gmm_ambiguous_percentage,
    agreement_percentage,
    compact_currency,
    percentage,
)

from components.charts import (
    SEGMENT_ORDER,
    build_segment_summary,
    customers_by_segment_chart,
    monetary_contribution_chart,
    customer_vs_monetary_share_chart,
)

from components.styles import (
    page_header,
)


# ---------------------------------------------------------
# Load final dashboard data
# ---------------------------------------------------------

(
    customers,
    model_metrics,
    segment_summary_file,
    strategy_mapping,
) = load_dashboard_data()


# ---------------------------------------------------------
# Page heading
# ---------------------------------------------------------

page_header(
    "Executive Overview",
    (
        "Headline customer segmentation, "
        "commercial value and model confidence "
        "results from the final analytical framework."
    ),
)


# ---------------------------------------------------------
# Calculate portfolio-level KPI values
# ---------------------------------------------------------

customer_count = total_customers(
    customers
)

monetary_value = total_monetary(
    customers
)

segment_count = total_segments(
    customers
)

high_value_customer_pct = (
    high_value_customer_percentage(
        customers
    )
)

high_value_monetary_pct = (
    high_value_monetary_percentage(
        customers
    )
)

kmeans_review_pct = (
    kmeans_review_percentage(
        customers
    )
)

gmm_ambiguous_pct = (
    gmm_ambiguous_percentage(
        customers
    )
)

model_agreement_pct = (
    agreement_percentage(
        customers
    )
)


# ---------------------------------------------------------
# KPI row 1 - Portfolio scale and commercial value
# ---------------------------------------------------------

st.markdown(
    "### Portfolio Overview"
)

kpi1, kpi2, kpi3, kpi4 = st.columns(
    4,
    gap="medium",
)

with kpi1:

    st.metric(
        label="Total Customers",
        value=f"{customer_count:,}",
        border=True,
        help=(
            "Unique customers in the final "
            "customer-level analytical dataset."
        ),
    )


with kpi2:

    st.metric(
        label="Total Monetary Value",
        value=compact_currency(
            monetary_value
        ),
        border=True,
        help=(
            "Observed Monetary value across "
            "the complete analysis period."
        ),
    )


with kpi3:

    st.metric(
        label="K-Means Segments",
        value=f"{segment_count}",
        border=True,
        help=(
            "Number of customer groups in "
            "the operational K-Means K=5 model."
        ),
    )


with kpi4:

    st.metric(
        label="High-Value Customers",
        value=percentage(
            high_value_customer_pct
        ),
        border=True,
        help=(
            "Combined customer share of "
            "High-Value Loyal Customers and "
            "High-Value Large-Order Buyers."
        ),
    )


# ---------------------------------------------------------
# KPI row 2 - Business concentration and confidence
# ---------------------------------------------------------

st.write("")

kpi5, kpi6, kpi7, kpi8 = st.columns(
    4,
    gap="medium",
)

with kpi5:

    st.metric(
        label="High-Value Monetary Contribution",
        value=percentage(
            high_value_monetary_pct
        ),
        border=True,
        help=(
            "Share of total Monetary value "
            "generated by the two high-value "
            "K-Means segments."
        ),
    )


with kpi6:

    st.metric(
        label="K-Means Review Group",
        value=percentage(
            kmeans_review_pct
        ),
        border=True,
        help=(
            "Customers meeting the broader "
            "K-Means boundary/review criteria. "
            "This is not an error rate."
        ),
    )


with kpi7:

    st.metric(
        label="GMM Ambiguous Membership",
        value=percentage(
            gmm_ambiguous_pct
        ),
        border=True,
        help=(
            "Customers meeting the final GMM "
            "ambiguity criteria. This is not "
            "a misclassification rate."
        ),
    )


with kpi8:

    st.metric(
        label="Aligned Model Agreement",
        value=percentage(
            model_agreement_pct
        ),
        border=True,
        help=(
            "Share of customers placed in "
            "corresponding K-Means and aligned "
            "GMM groups."
        ),
    )


# ---------------------------------------------------------
# Key commercial result
# ---------------------------------------------------------

st.write("")

with st.container(border=True):

    st.markdown(
        ":green-badge[KEY COMMERCIAL FINDING]"
    )

    st.markdown(
        f"""
        ### {high_value_customer_pct:.2f}% of customers generate
        {high_value_monetary_pct:.2f}% of total Monetary value
        """
    )

    st.caption(
        "High-Value Loyal Customers + "
        "High-Value Large-Order Buyers"
    )


# ---------------------------------------------------------
# Build portfolio summary from main customer dataset
# ---------------------------------------------------------

portfolio_summary = build_segment_summary(
    customers
)


# ---------------------------------------------------------
# Add final K-Means strategy information
# ---------------------------------------------------------

kmeans_strategy = (
    strategy_mapping[
        strategy_mapping["Model"]
        == "K-Means K=5"
    ]
    .copy()
)


strategy_columns = kmeans_strategy[
    [
        "Business_Segment",
        "Primary_Objective",
        "Recommended_Action",
        "Primary_KPI",
        "Operational_Priority",
    ]
]


portfolio_summary = (
    portfolio_summary
    .merge(
        strategy_columns,
        left_on="Segment_Name",
        right_on="Business_Segment",
        how="left",
    )
    .drop(
        columns=["Business_Segment"]
    )
)


# ---------------------------------------------------------
# Segment exploration controls
# ---------------------------------------------------------

st.write("")

st.markdown(
    "### Explore the Segment Portfolio"
)

st.caption(
    "The headline KPI cards above represent the "
    "complete customer portfolio. The controls below "
    "filter the comparison visuals and action table "
    "while retaining each segment's share of the "
    "complete portfolio."
)


filter_box = st.container(
    border=True
)


with filter_box:

    filter_col1, filter_col2 = st.columns(
        2,
        gap="large",
    )

    with filter_col1:

        available_segments = [
            segment
            for segment in SEGMENT_ORDER
            if segment
            in portfolio_summary[
                "Segment_Name"
            ].tolist()
        ]

        selected_segments = st.multiselect(
            "Customer segments",
            options=available_segments,
            default=available_segments,
            key="executive_segment_filter",
            help=(
                "Choose which K-Means segments "
                "to display in the comparison visuals."
            ),
        )


    with filter_col2:

        priority_order = [
            "Low",
            "Medium",
            "High",
            "Very High",
            "Critical",
        ]

        available_priorities = [
            priority
            for priority in priority_order
            if priority
            in portfolio_summary[
                "Operational_Priority"
            ].dropna().unique().tolist()
        ]

        selected_priorities = st.multiselect(
            "Operational priorities",
            options=available_priorities,
            default=available_priorities,
            key="executive_priority_filter",
            help=(
                "Filter the portfolio according "
                "to the final operational priority."
            ),
        )


# ---------------------------------------------------------
# Apply visual filters
# ---------------------------------------------------------

visible_summary = portfolio_summary[
    (
        portfolio_summary[
            "Segment_Name"
        ].isin(
            selected_segments
        )
    )
    &
    (
        portfolio_summary[
            "Operational_Priority"
        ].isin(
            selected_priorities
        )
    )
].copy()


if visible_summary.empty:

    st.warning(
        "No customer segments match the current "
        "combination of filters."
    )

    st.stop()


# ---------------------------------------------------------
# Main segment charts
# ---------------------------------------------------------

st.write("")

chart_col1, chart_col2 = st.columns(
    2,
    gap="large",
)


with chart_col1:

    st.markdown(
        "#### Customers by Segment"
    )

    st.caption(
        "Number of customers assigned to each "
        "operational K-Means segment."
    )

    customer_chart = (
        customers_by_segment_chart(
            visible_summary
        )
    )

    st.plotly_chart(
        customer_chart,
        width="stretch",
        key="executive_customer_chart",
        config={
            "displayModeBar": False
        },
    )


with chart_col2:

    st.markdown(
        "#### Monetary Contribution by Segment"
    )

    st.caption(
        "Each segment's contribution to total "
        "observed Monetary value."
    )

    monetary_chart = (
        monetary_contribution_chart(
            visible_summary
        )
    )

    st.plotly_chart(
        monetary_chart,
        width="stretch",
        key="executive_monetary_chart",
        config={
            "displayModeBar": False
        },
    )


# ---------------------------------------------------------
# Customer-share vs Monetary-share comparison
# ---------------------------------------------------------

st.write("")

st.markdown(
    "### Customer Share versus Monetary Contribution"
)

st.caption(
    "This comparison shows whether a segment's "
    "commercial contribution is proportional to "
    "its share of customers."
)


share_chart = (
    customer_vs_monetary_share_chart(
        visible_summary
    )
)

st.plotly_chart(
    share_chart,
    width="stretch",
    key="executive_share_chart",
    config={
        "displayModeBar": False
    },
)


# ---------------------------------------------------------
# Final segment action plan
# ---------------------------------------------------------

st.write("")

st.markdown(
    "### Segment Action Summary"
)

st.caption(
    "Business actions are linked to the final "
    "K-Means customer profiles rather than "
    "being generated from model confidence alone."
)


action_table = visible_summary[
    [
        "Segment_Name",
        "Customer_Count",
        "Customer_Share",
        "Monetary_Share",
        "Primary_Objective",
        "Primary_KPI",
        "Operational_Priority",
    ]
].copy()


action_table = action_table.rename(
    columns={
        "Segment_Name":
            "Customer Segment",

        "Customer_Count":
            "Customers",

        "Customer_Share":
            "Customer Share",

        "Monetary_Share":
            "Monetary Share",

        "Primary_Objective":
            "Objective",

        "Primary_KPI":
            "Target KPI",

        "Operational_Priority":
            "Priority",
    }
)


action_table[
    "Customer Share"
] = action_table[
    "Customer Share"
].map(
    lambda value:
        f"{value:.2f}%"
)


action_table[
    "Monetary Share"
] = action_table[
    "Monetary Share"
].map(
    lambda value:
        f"{value:.2f}%"
)


st.dataframe(
    action_table,
    hide_index=True,
    width="stretch",
)


# ---------------------------------------------------------
# Model role explanation
# ---------------------------------------------------------

st.write("")

model_col1, model_col2 = st.columns(
    2,
    gap="large",
)


with model_col1:

    with st.container(
        border=True
    ):

        st.markdown(
            "#### Primary Operational Model"
        )

        st.markdown(
            "**K-Means K=5**"
        )

        st.caption(
            "Used for customer segment assignment, "
            "business profiling and operational "
            "strategy mapping."
        )


with model_col2:

    with st.container(
        border=True
    ):

        st.markdown(
            "#### Supporting Analytical Model"
        )

        st.markdown(
            "**GMM C5 Spherical**"
        )

        st.caption(
            "Used as an additional probabilistic "
            "membership and assignment-confidence "
            "evidence layer."
        )


# ---------------------------------------------------------
# Methodological note
# ---------------------------------------------------------

st.info(
    (
        "K=2 remains the broad statistical "
        "K-Means benchmark. K=5 is retained as "
        "the operational segmentation because it "
        "provides five stable and commercially "
        "interpretable customer groups. "
        "The dashboard does not treat clustering "
        "agreement or confidence as classification "
        "accuracy."
    )
)